/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell-XPS
 */
public class manbodyparts extends javax.swing.JFrame {

    /**
     * Creates new form bodyparts
     */
    public manbodyparts() {
        initComponents();
        setVisible(true);
        setSize(600,490);
        brainlbl.setVisible(false);
        eyeslbl.setVisible(false);
        heartlbl.setVisible(false);
        chestlbl.setVisible(false);
        legslbl.setVisible(false);
        stomachlbl.setVisible(false);
        //jPanel1.setVisible(false);
       // jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brainlbl = new javax.swing.JLabel();
        eyeslbl = new javax.swing.JLabel();
        heartlbl = new javax.swing.JLabel();
        chestlbl = new javax.swing.JLabel();
        legslbl = new javax.swing.JLabel();
        stomachlbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        homebutton = new javax.swing.JButton();
        searchtb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell-XPS\\Desktop\\UPR MEN2.jpg")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 58, 149, 82);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easymedication/LW MEN.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 149, 261);

        brainlbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brainlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brainlbl.setText("Brain");
        brainlbl.setToolTipText("");
        getContentPane().add(brainlbl);
        brainlbl.setBounds(240, 80, 98, 38);

        eyeslbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eyeslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eyeslbl.setText("Eyes");
        getContentPane().add(eyeslbl);
        eyeslbl.setBounds(393, 82, 100, 40);

        heartlbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heartlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heartlbl.setText("Heart");
        getContentPane().add(heartlbl);
        heartlbl.setBounds(260, 160, 76, 36);

        chestlbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chestlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chestlbl.setText("Chest");
        getContentPane().add(chestlbl);
        chestlbl.setBounds(400, 160, 76, 36);

        legslbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        legslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        legslbl.setText("Legs");
        getContentPane().add(legslbl);
        legslbl.setBounds(260, 280, 76, 36);

        stomachlbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stomachlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stomachlbl.setText("Stomach");
        getContentPane().add(stomachlbl);
        stomachlbl.setBounds(250, 220, 110, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Back");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 420, 80, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell-XPS\\Desktop\\newbackground.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 44, 570, 440);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        searchtb.setForeground(new java.awt.Color(204, 204, 204));
        searchtb.setText("search...");
        searchtb.setToolTipText("");
        searchtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchtbMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchtbMouseReleased(evt);
            }
        });
        searchtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtbActionPerformed(evt);
            }
        });
        searchtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtbKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtbKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(searchtb, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homebutton)
                    .addComponent(searchtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 580, 45);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //jPanel1.setVisible(true);
        brainlbl.setVisible(true);
        eyeslbl.setVisible(true);
        heartlbl.setVisible(false);
        chestlbl.setVisible(false);
        legslbl.setVisible(false);
        stomachlbl.setVisible(false);
       // jPanel2.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //jPanel2.setVisible(true);
        brainlbl.setVisible(false);
        eyeslbl.setVisible(false);
        heartlbl.setVisible(true);
        chestlbl.setVisible(true);
        legslbl.setVisible(true);
        stomachlbl.setVisible(true);
       // jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        home obj1=new home();
        obj1.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void searchtbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtbMousePressed
        searchtb.setText("");
    }//GEN-LAST:event_searchtbMousePressed

    private void searchtbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchtbMouseReleased
        searchtb.setText("");
    }//GEN-LAST:event_searchtbMouseReleased

    private void searchtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtbActionPerformed

    private void searchtbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtbKeyPressed
        searchtb.setText("");
    }//GEN-LAST:event_searchtbKeyPressed

    private void searchtbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtbKeyReleased
        searchtb.setText("");
    }//GEN-LAST:event_searchtbKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        home2 obj1=new home2();
        obj1.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manbodyparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manbodyparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manbodyparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manbodyparts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manbodyparts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brainlbl;
    private javax.swing.JLabel chestlbl;
    private javax.swing.JLabel eyeslbl;
    private javax.swing.JLabel heartlbl;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel legslbl;
    private javax.swing.JTextField searchtb;
    private javax.swing.JLabel stomachlbl;
    // End of variables declaration//GEN-END:variables
}
