
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;




public class mpage extends javax.swing.JFrame {

    
    public mpage() {
        initComponents();
        setSize(600,479);
        setVisible(true);
        jp_view.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bk_lb = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        add_bt = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jp_add = new javax.swing.JPanel();
        jp_view = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();

        bk_lb.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenovo\\Desktop\\WP_MEDICAL.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jp1.setLayout(null);

        add_bt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        add_bt.setText("VIEW");
        add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btActionPerformed(evt);
            }
        });
        jp1.add(add_bt);
        add_bt.setBounds(3, 0, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EDIT", "ADD", "DELETE" }));
        jp1.add(jComboBox1);
        jComboBox1.setBounds(110, 0, 100, 30);

        jp_add.setLayout(null);

        jp_view.setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jp_view.add(jComboBox2);
        jComboBox2.setBounds(0, 32, 110, 20);

        jp_add.add(jp_view);
        jp_view.setBounds(0, 0, 110, 100);

        jp1.add(jp_add);
        jp_add.setBounds(0, 0, 440, 360);

        getContentPane().add(jp1);
        jp1.setBounds(0, 0, 440, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
          
          Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/easymed","root","mysql");
          
        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          ResultSet rs=stmt.executeQuery("select * from medicines");
          while(rs.next()==true)
          {
              
          }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_add_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bt;
    private javax.swing.JLabel bk_lb;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp_add;
    private javax.swing.JPanel jp_view;
    // End of variables declaration//GEN-END:variables
}
