

import java.io.*;
import java.net.*;
import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;

public class shoplogin extends javax.swing.JFrame {

    Connection conn;
    public shoplogin()
    {
        initComponents();
        setVisible(true);
        setSize(600,490);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_bt = new javax.swing.JButton();
        pass_lb = new javax.swing.JLabel();
        password_tf = new javax.swing.JTextField();
        login_lb = new javax.swing.JLabel();
        login_tf = new javax.swing.JTextField();
        bk_lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        login_bt.setBackground(new java.awt.Color(204, 204, 0));
        login_bt.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        login_bt.setText("LOGIN");
        login_bt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        login_bt.setFocusPainted(false);
        login_bt.setOpaque(false);
        login_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btActionPerformed(evt);
            }
        });
        getContentPane().add(login_bt);
        login_bt.setBounds(160, 359, 220, 50);

        pass_lb.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        pass_lb.setText("PASSWORD");
        getContentPane().add(pass_lb);
        pass_lb.setBounds(40, 220, 240, 50);

        password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_tfActionPerformed(evt);
            }
        });
        getContentPane().add(password_tf);
        password_tf.setBounds(310, 220, 220, 40);

        login_lb.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        login_lb.setText("SHOPNAME");
        getContentPane().add(login_lb);
        login_lb.setBounds(40, 120, 150, 40);

        login_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_tfActionPerformed(evt);
            }
        });
        getContentPane().add(login_tf);
        login_tf.setBounds(310, 130, 210, 40);
        getContentPane().add(bk_lb);
        bk_lb.setBounds(0, 0, 600, 490);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SHOPKEEPER LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 320, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easymedication/newbackground.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -40, 580, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
          
          Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/easy_med","root","mysql5");
          
        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
          ResultSet rs=stmt.executeQuery("select * from login where name = ' "+login_tf+"' and password =+ ' "+password_tf+"'");
            if(rs.next())
            {
               mpage ob=new mpage();
               dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"either login name or password incorrect");
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_login_btActionPerformed

    private void login_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_tfActionPerformed

    private void password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shoplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shoplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shoplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shoplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shoplogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bk_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login_bt;
    private javax.swing.JLabel login_lb;
    private javax.swing.JTextField login_tf;
    private javax.swing.JLabel pass_lb;
    private javax.swing.JTextField password_tf;
    // End of variables declaration//GEN-END:variables
}
